from pathlib import Path
import json
h=Path(__file__).resolve().parents[4];d=h/'docs/verification/latest_six_20261005'
m=json.loads((d/'metrics.json').read_text());batch=json.loads((h/'logs/latest_six_20261005_batch/matrix.json').read_text());assert len(m)==6 and batch['status']=='COMPLETE'
r=json.loads((d/'release_truth.json').read_text());count=sum(len(v['drops']) for v in r);wrong=sum(not x['label_matches'] for v in r for x in v['drops']);passes=sum(v['status']=='PASS' for v in m)
s=f'''\n## 结论与下一步\n\n六轮固定同版全部结束，原始Gate为{passes}/6通过，共{count}次模拟释放，按释放时机体最近真实靶标核对，标签不符{wrong}次。矩形两seed均完成正确三投、走廊与H落地，适合作为下一轮同版回归对照；样本仅两轮，不等于成功率已标定。三种航线参数化留在高位研究中，本次没有覆盖整机候选的默认航线，也没有上板。\n\n### 旧标签误投已在真实触发路径被阻断\n\n- seed38矩形仍出现高空将碉堡记成panzer的竞争线索，但低空在ROS80.702s输出LOW_VIEW_LABEL_RESOLVED=pillbox，80.709s将旧panzer目标延后；未在碉堡投递，最终前往真正panzer完成释放。旧八轮同配置曾在碉堡上方错投，本轮不是靠消失了同一触发条件来宣称修复。\n- seed31双扫描线同样发生低空改判pillbox，再前往真正panzer；seed38双线、三线也观察到LOW_VIEW_LABEL_RESOLVED。检测器高空类别混淆仍存在，记忆修复负责不让异类新观测维持旧confirmed，不等于模型本身不再误检。\n- 三线seed38撤销碉堡错误线索后没有足够的真实panzer高位记忆可直接重访，进入LOW_COVERAGE；到约ROS318s才接近真实panzer完成后续链。这条额外遍历是显著耗时来源。\n\n### seed38双扫描线：真实空中接触，不能按落地收尾豁免\n\n两投后在ROS103.251s进入LOW_COVERAGE，136.178s与固定juniper_Tree_1发生机体碰撞包络接触，FC中心真实离地约1.49m。接触由55×55×40cm机体包络记录，深度约0.096mm、力约0.167N；这是非零真实接触，不是落地后超时，也不能因碰撞轻微就算通过。\n\n接触前两秒（统计截至接触前0.1s）LIO水平真值误差最大约5.3mm、竖直8.7mm；飞控水平约1.77cm、竖直3.81cm。没有支持“本次碰撞由LIO跳变导致”的证据。机体中心到已发布B样条的最近空间距离约17.7cm，偏向树体；设定点本身存在主动前视，因此不把当前设定点与机体间约0.8m距离当成同步轨迹误差。\n\n![弯道跟踪、机体包络与定位误差](collision_snake2_38.png)\n\n更应优先核查弯道前视/跟踪、三维机体扫掠和预留净空；本包没有完整占据点云，不能断言规划地图完全正确或把责任完全归给控制。旧八轮三线seed38也曾在同一树附近接触，说明补搜绕树是需专门覆盖的失败路径。后续可做离线轨迹与机体扫掠复核，再修改相关路径并获得新的仿真授权后回归；本次未为了通过验收缩小包络/膨胀，未重跑失败轮择优。\n\n### seed38三扫描线：已落地，但软件终态交接未闭合

该轮物理触地为任务403.984s（ROS415.410s），其后196.064s才触发任务超时；LAND段图中的约202.5s包含这段地面等待，不是一直飞行。原始Gate为manager_failed/landing_deadline_reached；按用户口径是三投且无碰撞落地完成，六轮物理完整飞行为5/6。该轮在ROS417.369s记录LANDED_STATE_ON_GROUND，419.568s记录armed=false，真值随后持续静止；实时Bridge快照却持续显示landing_settle.reason=control_state_not_landing（见landing_tail_snake3_38_live_bridge.json）。生产_update_landing在积累settle前要求_control_state==3，因此旧控制离开LAND后不能继续确认已经完成的落地。

日志在同一419.568s明确记录flight_controller_control_lost；externalLandingStateCallback把上锁后的OFFBOARD状态走进控制丢失分支，failExternalLanding将Drone_mode置为Run_point(1)，与实时/detect/point_class=1一致。H在410.349s已经通过10帧对齐。因此本轮收尾阻塞不是H没识别或LIO空中跳变，见landing_tail_snake3_38_evidence.json。原始Gate保持记录，物理落地按用户口径单独认定。后续应检查正常LAND事务、更新的ON_GROUND/上锁反馈与接管取消之间的时序，修复落地完成确认和旧状态退出的竞争；不得简单绕开人工接管取消。本批保持源码固定，未边跑边改或通过改Gate隐藏问题。

### 节时与限高必须分别评价\n\n首四个完整通过轮的全程水平速度P95约0.84–0.89m/s，不能用设定速度上限代替实测。相对旧未优化矩形，当前矩形seed31物理触地反而慢13.98s，seed38慢9.61s。相对旧已优化矩形，seed31快29.50s；seed38旧轮有错靶，不能据此作等质量节时宣传。矩形两seed投后恢复合计由旧基线9.478/10.788s减到7.057/6.774s，分别缩短2.421/4.014s；局部衔接收益被其他阶段抵消。总体尚无“全面提速”的结论，应看搜索/复核/投后/走廊分段，而不是继续直接加大速度。\n\n当前矩形31、矩形38和三线31在走廊区域真实FC高度分别达到约1.058、1.049、1.068m，双线31约0.984m。规划/控制参考点共同1.0m限制已经接通，但真实跟踪超调仍需处理。旧Gate使用1.2m区域门槛，因此这些PASS不代表严格1.0m物理限高已经验收。进一步对齐峰值附近的记录：矩形31真值1.058m、FC估计1.005m、指令0.937m；三线31真值1.068m、FC估计0.983m、指令0.900m；矩形38真值1.049m、FC估计0.982m、指令0.900m（时间差均小于50ms，见corridor_peak_context.json）。因此既有FC高度估计偏差，也有相对设定点的实际跟踪偏差，不能笼统认定规划器发布了超高轨迹。不要通过调高验收门槛或忽略真值掩盖余量问题。\n\n### 最接近整机闭环的安排\n\n1. 保持现场0.5m/s和矩形，先做06高位优先同版回归（记忆改判、真实三投、返起飞点）；无需重跑全部历史成功专项。\n2. 做03强化H完整落地，再做04实测门前/门后引导点→H，包含遥控接管和走廊真实限高。\n3. 修复并回归本次LOW_COVERAGE树体接触，再启用快速整场；08使用已经验证的参数完成同一轮三投→走廊→H，是最终闭环核心验收。\n4. 09高速采集并行提供0.5/1.0/1.2m/s、明暗条件数据，验证各类连续识别、曝光模糊、EV/LIO年龄；高速采集成功不替代快速投递整场验收。\n\n现有SITL验证标准80cm H，不能替代实拍反光、差光照和板端RKNN表现。真实舵机、落点、轻量录包、人工OFFBOARD与接管、板端多线程实时性仍按手册验收。\n'''
p=d/'REPORT.md';text=p.read_text();marker='\n## 结论与下一步\n';text=text.split(marker)[0]+s;p.write_text(text)
idx=d/'index.html';text=idx.read_text();note=f'<p><strong>六轮完成：{passes}/6原始Gate通过，{count}次模拟释放中错靶{wrong}次；seed38双线存在真实树体接触。</strong>三投不等于整场成功。视频警戒线沿用旧区域Gate 1.2m，规划共同约束为1.0m；seed38三线末尾含约196秒静止等待，不计作持续飞行。<a href="collision_snake2_38.png">碰撞分析图</a>；走廊真实限高超调另见报告。</p>'
text=text.replace('<h1>最新补丁六轮整机对比</h1>','<h1>最新补丁六轮整机对比</h1>'+note);idx.write_text(text)
print('FINAL conclusions',passes,count,wrong)